name: Docker Container

on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest
    container:
      image: node:14-slim
    steps:
      - name: Check node version in container
        run: |
          node -v
          cat /etc/os-release
      - name: Check step not version
        uses: docker://node:17-stretch
        with:
          entrypoint: /usr/local/bin/node
          args: -v
