name: Matrix
on: [push]

jobs:
  node-version:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [macos-latest, ubuntu-latest, windows-latest]
        exclude:
          - os: windows-latest
            node_version: 10
    steps:
      - name: Node node-version
        run: echo ${{matrix.os}} ${{matrix.node_version}}
      - name: os
        run: ${{matrix.os}}
