name: Matrix
on: [push]

jobs:
  node-version:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [macos-latest, ubuntu-latest, windows-latest]
        exclude:
          - os: windows-latest
            node_version: 10
    steps:
      - name: Node node-version
        run: |
          node -v
          echo ${{matrix.os}}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Node node-version After
        run: |
          node -v
          echo ${{matrix.os}}
