name: Shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo shell command
        run: echo "Hello World"
      - name: Check versions
        run: |
          node -v
          npm -v
      - name: Python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-powerShell-commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Get bash current location
        run: pwd
        shell: bash
